Bb final decoding
int-brain-lab/paper-brain-wide-map pull request #7
Opened 2022-12-11 00:26 UTC by bensonbrandon

This is the code used for BWM decoding.  I have added to the pipeline for post-processing and updated the settings.

2022-12-14 16:01 UTC, themattinthehatt requested changes
Hey Brandon, looks good overall. I left various comments in the files themselves. Some misc comments:

* `data_checks/.DS_store` - can delete this
* it would be great if, inside `brainwidemap/decoding` you add a `README.md` file that walks users through the whole pipeline. Step 0: you want to cache data, for this and this reason. that's what `00_data_caching.py` does. in reality we want to parallelize this on a cluster to speed up the process, and so you run `slurm_data_caching.sh`; here are the relevant SBATCH commands, here's how you run this from the command line in slurm. After the data is cached, the next step is to create a dataframe of imposter sessions for this and this reason, etc. This will be super useful for anyone who wants to understand the process, as well as helpful for you if you set this aside for a few months (say during paper revisions) and need to come back to it later :)

2023-01-07 06:27 UTC, bensonbrandon commented on brainwidemap/decoding/00_data_caching.py
> +BAD_PIDS = []
yes, it is overwriting the list.  I used the list in the past, but it is no longer necessary to skip those PIDS.   I can delete the list, and on the off chance that we need it again, we could dig it up from an old commit.

2023-01-07 21:07 UTC, bensonbrandon commented on brainwidemap/decoding/02_generate_imposter_df.py
> +    if np.random.rand() > 1.1:
Yes, that's what it is used for.  With the current value of 1.1 the condition is never True, so I will go ahead and delete the statement altogether.

2023-01-07 21:11 UTC, bensonbrandon commented on brainwidemap/decoding/02_generate_imposter_df.py
> +        if (trialsdf.index.size > 400) \
oh I see.  This would be redundant with the session loader, right?

2023-01-07 21:25 UTC, bensonbrandon commented on brainwidemap/decoding/03_decode_single_session.py
> +if (job_repeat + 1) * params['n_pseudo_per_job'] > params['n_pseudo']: #TODO bb thinks this is wrong, bb flipped from <= to >, should be good now
ok, I'm happy. deleted comment

2023-01-08 00:31 UTC, bensonbrandon commented on brainwidemap/decoding/04_format_slurm.py
> +'''
yes, deleted

2023-01-09 18:02 UTC, bensonbrandon commented on brainwidemap/decoding/02_generate_imposter_df.py
> +    if np.random.rand() > 1.1:
okay, yes it was only for subselecting sessions. I deleted it.

2023-01-09 18:02 UTC, bensonbrandon commented on brainwidemap/decoding/02_generate_imposter_df.py
> +        if (trialsdf.index.size > 400) \
okay

2023-01-09 18:02 UTC, bensonbrandon commented on brainwidemap/decoding/functions/decoding.py
> +                    ys_wmask = [target_vals_list[m] for m in np.squeeze(np.where(mask))]
thanks

2023-01-09 18:12 UTC, bensonbrandon commented on brainwidemap/decoding/settings_for_BWM_figure/settings_block.py
> +import numpy as np
There are settings which don't change in BWM, but do change for other analyses, for example the prior paper analysis.  When I change settings for comparing with the prior paper, I want to be confident that I don't overwrite the BWM settings, so I make a new file.

2023-01-10 17:12 UTC, themattinthehatt requested changes
@bensonbrandon solid updates - I left a couple more comments that will be easy to address.

also, I think we should rename the slurm files to have the corresponding python file number prefix, i.e. change `slurm_data_caching.sh` to `00_slurm_data_caching.sh` etc to keep everything as consistent as possible.

2023-01-10 17:12 UTC, themattinthehatt commented on brainwidemap/decoding/05_generate_summary_tables.py
> +MIN_SESS_PER_REG = 1
this should also go in the params files

2023-01-10 17:12 UTC, themattinthehatt commented on brainwidemap/decoding/README.md
> +.  The total number of jobs required will be the number of sessions * ciel(n_pseudo / n_pseudo_per_job).
typo in `ceil`

2023-01-10 17:12 UTC, themattinthehatt commented on brainwidemap/decoding/README.md
> +slurm_decode.sh, excluding diretcory, is 'ds_bwmrelease_3_.%a.err', then you will want to remember the
typo in `directory`

2023-01-10 17:12 UTC, themattinthehatt commented on brainwidemap/decoding/README.md
> +# Pipeline for running BWM decoding analysis
nice job @bensonbrandon, this looks great! very nice summary.

one comment - you can update the code snippets from
'''
sbatch stuff.py
'''
to 
```
sbatch stuff.py
```
by replacing the three apostrophes ''' with three backticks ``` and the markdown will render more nicely

2023-01-12 19:10 UTC, bensonbrandon commented on brainwidemap/decoding/00_data_caching.py
> +min_trials = 150
So the caching min_trials could be different than the settings.py min_trials.  I suppose we should cache everything by setting this min_trials=0, and then the decoding script 03... will take care of filtering the cached trials to meet the settings.py min_trials.  Does that seem okay to you?

2023-01-12 19:38 UTC, bensonbrandon commented on brainwidemap/decoding/03_decode_single_session.py
> +min_trials = 150
agreed.  done

2023-01-13 00:50 UTC, themattinthehatt approved these changes

2023-01-13 00:50 UTC, merged